### ISSUE TITLE
proposal: focus just on a pomodoro to-do list

### ISSUE THREAD

**Issue by jayrbolton** [jayrbolton/taskgarden#10]
Proposal to make a mytomatoes.com clone but with much nicer design using node.js (and perhaps stateful-dom?)

General features:
- Start tomato button
- Countdown timer
- Squash tomato button (if you lose focus)
- Record what you did when the tomato finishes
- history of stuff you did day-by-day

Bonus points / other ideas:
- Inbox to-list -- write down what you need to do beforehand, then hit a tomato button next to each item to start working on it
- Collaborative lists / team features (definitely think about this after the above mvp)
- Prioritization controls on the inbox
- Integration with github!

@mrdougwright  @yutakahoulette plz leave feedback and ideas here

**Comment by yutakahoulette-zz** [comment]
Off-the-top-of-my-head-super-duper-minimal-idea:
- hardly any text
-  turn the whole screen into a progress bar, so if you are halfway done (10 minutes in), then half of the screen will be a certain color (this would be the timer)
- on the left or right side of the screen, you could have circles that represent the number of poms you've done that day (the day's history)

Other ideas:
- keeps track of record number of poms
- calendar view (or it could be abstracted like the green squares in the github history)

**Comment by jayrbolton** [comment]
I like the giant-progress-bar idea, that'd be fun

I think we should keep open to the idea of having a simple to-do list as well. I want to be able to sit down in the morning, write out the to-do list of stuff I want to do today, and then pull items off that list and do tomatoes on them. That way you can also see how many poms each item on your list ended up taking. Could still have crazy minimal progress bar since you don't need to see anything else at all while you're doing a tomato. You're just doing the tomato! Once you're done with the tomato, you pop back onto the list

Calendar, or at least tasks that can be delayed to a future date, is also a great idea for post-mvp

**Comment by jayrbolton** [comment]
Another idea 
- Show a stack of pomodoros you did today alongside a stack of the average number of pomodoros you usually complete in a day so you can try to match it

Weird idea, definitely not mvp and not saying we should really do this:
- Take the garden metaphor a lot further:
  - Completing tasks that are urgent pulls weeds
  - Completing tasks that are important waters your garden
  - The more 25-minute units you complete, the more sun your garden gets
  - Maybe not that exactly... but something like that...

**Comment by mrdougwright** [comment]
The tomatoes are growing from the garden. Loving all these ideas.

**Comment by jayrbolton** [comment]
@yutakahoulette @mrdougwright after a lot of thinking and playing around, I think we should try to make the front-end with BaconJS + D3 + Browserify. I think it'll be really powerful and a good learning experience.

**Comment by mrdougwright** [comment]
I'm down. Trust your judgement.

**Comment by jayrbolton** [comment]
Another random to-do list idea that I would really like, just putting it here:
- Have separate views for "backlog" and "working on right now".
- In your backlog view, you go through and classify everything with dates, priority, context, due dates, difficulty, and time
- In your "working on right now" view, you only get a list of 3 items, no more. These three items are automatically calculated by the app using the above data as the ones you should be doing right now.
- This way, you only ever need to think about three items to do at any given time
