### ISSUE TITLE
proposal: focus just on a productivity app for software developers using git

### ISSUE THREAD

**Issue by jayrbolton** [jayrbolton/taskgarden#8]
Was thinking that this won't actually be very useful for a role like wendy who has to answer a lot of calls and do a lot of in-the-moment tasks like phonecalls

However, software developers have a very cut-and-dry workflow, where they pull down tasks, put in focused time on them, and either finish them, fail at them, or fork them into other tasks. 

It could be really cool to just focus on the vertical of developers and basically make an app that uses the Github API and makes a wrapper around your git repository to turn your team's work on the repo into a collaborative to-do list with voting, prioritization, points, and visualization.

@mrdougwright

**Comment by mrdougwright** [comment]
Sounds good. And could Wendy access, to monitor our progress and up/down vote tasks and things?
